apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-external-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    # WATCH OUT: This MUST perfectly match the metadata.name in secret-store.yaml!
    name: vault-backend
    kind: SecretStore
  target:
    name: postgres-secret
    # WHY Owner: If you delete this ExternalSecret file, Kubernetes will automatically delete 
    # the 'postgres-secret' it generated. This prevents orphaned secrets from floating around.
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      # WHY bunny-app: This must perfectly match the path you typed in your 'vault kv put' command!
      key: bunny-app
      property: POSTGRES_PASSWORD
