apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  # WATCH OUT: SecretStores are namespace-scoped. It can only fetch secrets for pods in this exact namespace.
  name: vault-backend
spec:
  provider:
    vault:
      # WHY: This is the internal DNS address of the Vault pod we installed via Helm.
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      # WHY v2: Vault has two versions of its Key-Value engine. Dev mode defaults to v2.
      # If you put v1 here, it will silently fail to read your secret.
      version: "v2"
      auth:
        # WHY NOT HARDCODE: We never hardcode passwords in GitOps.
        # This tells ESO to look for a Kubernetes Secret named 'vault-token' to get the login password.
        tokenSecretRef:
          name: vault-token
          key: token
